language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql TYPO3=master INTEGRATION=master
  - DB=mysql TYPO3=TYPO3_6-1 INTEGRATION=master
  - DB=mysql TYPO3=TYPO3_6-0 INTEGRATION=master

matrix:
  include:
    - php: 5.3
      env: DB=mysql TYPO3=TYPO3_4-7 INTEGRATION=TYPO3_4-7
    - php: 5.3
      env: DB=mysql TYPO3=TYPO3_4-6 INTEGRATION=TYPO3_4-7
    - php: 5.3
      env: DB=mysql TYPO3=TYPO3_4-5 INTEGRATION=TYPO3_4-7
    - php: 5.2
      env: DB=mysql TYPO3=TYPO3_4-5 INTEGRATION=TYPO3_4-7

before_script:
  - sudo apt-get update && sudo apt-get install git
# Install  build dependencies
  - cd ..
  - git clone --single-branch --branch $INTEGRATION --depth 1 git://github.com/typo3-ci/TYPO3-Travis-Integration.git build-environment
  - git clone --single-branch --branch $TYPO3 --depth 1 https://github.com/TYPO3/TYPO3.CMS.git core
  - source build-environment/install-helper.sh
  - if [[ "$TRAVIS_PHP_VERSION" != "5.5" ]]; then installPhpModule igbinary; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "5.3" ]]; then installPhpModule -y apc; fi

# Install rudimentary TYPO3
  - git clone --single-branch --branch $TYPO3 --depth 1 git://git.typo3.org/TYPO3v4/Distributions/Introduction.git build-environment/Introduction
  - mv core/typo3 .
  - if [[ -d core/t3lib ]]; then mv core/t3lib . ; fi
  - mv build-environment/typo3conf .
  - git clone --single-branch --branch master --depth 1 git://git.typo3.org/TYPO3v4/Extensions/phpunit.git typo3conf/ext/phpunit/
  - mv typo3-ext-flvplayer2 ./typo3conf/ext/flvplayer2
  - mkdir fileadmin
  - mkdir uploads
  - if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/Introduction/typo3conf/ext/introduction/Resources/Private/Subpackages/Introduction/Database/introduction.sql; fi
  - if [[ "$DB" == "mysql" && -f build-environment/dbimport/cache_tables.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/cache_tables.sql; fi
  - if [[ "$DB" == "mysql" && -f  build-environment/dbimport/cli_users.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/cli_users.sql; fi
  - if [[ -f typo3conf/LocalConfiguration.php && -f typo3conf/ext/flvplayer2/Build/LocalConfiguration.php ]]; then cp typo3conf/ext/flvplayer2/Build/LocalConfiguration.php typo3conf/LocalConfiguration.php; fi
  - if [[ -f typo3conf/PackageStates.php && -f typo3conf/ext/flvplayer2/Build/PackageStates.php ]]; then cp typo3conf/ext/flvplayer2/Build/PackageStates.php typo3conf/PackageStates.php; fi
  - if [[ -f typo3conf/localconf.php && -f typo3conf/ext/flvplayer2/Build/localconf.php ]]; then cp typo3conf/ext/flvplayer2/Build/localconf.php typo3conf/localconf.php; fi

script:
  - pushd . && cd $PWD/typo3conf/ext/flvplayer2 && phpLint all && popd
  - php $PWD/typo3/cli_dispatch.phpsh phpunit -c typo3conf/ext/flvplayer2/Tests/Build/UnitTests.xml
